In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
df = pd.read_csv("../data/delaney-mordred.csv")
train, test = train_test_split(df, random_state=42, test_size=0.2)

In [2]:
train

,name,smiles,logS,mordred_0,mordred_1,mordred_2,mordred_3,mordred_4,mordred_5,mordred_6,...,mordred_1603,mordred_1604,mordred_1605,mordred_1606,mordred_1607,mordred_1608,mordred_1609,mordred_1610,mordred_1611,mordred_1612
876,"3,5-Dimethylphenol",Cc1cc(C)cc(O)c1,-1.400,6.692130,6.355891,0.0,0.0,10.128990,2.236068,4.472136,...,8.760767,37.736937,122.073165,6.424903,84.0,9.0,42.0,45.0,4.083333,2.000000
712,Methyl propyl ether,CCCOC,-0.390,2.828427,3.146264,0.0,0.0,5.464102,1.732051,3.464102,...,6.192362,25.583106,74.073165,4.938211,20.0,2.0,14.0,12.0,2.750000,1.500000
554,2-Bromonapthalene,Brc1ccc2ccccc2c1,-4.400,8.554231,7.309128,0.0,0.0,14.426921,2.333244,4.666488,...,9.225721,41.498380,205.973112,11.442951,144.0,14.0,56.0,64.0,3.083333,2.444444
688,Simetryn,CSc1nc(nc(n1)N(C)C)N(C)C,-2.676,10.256174,9.749792,0.0,0.0,16.801602,2.338361,4.676722,...,9.317310,45.172259,213.104816,7.348442,296.0,19.0,66.0,74.0,6.555556,3.222222
780,Benzo(j)fluoranthene,c1ccc2c3c(ccc2c1)c4cccc5cccc3c45,-8.000,16.647042,12.422860,0.0,0.0,28.211841,2.605456,5.030003,...,10.348782,69.571934,252.093900,7.877934,678.0,39.0,120.0,152.0,3.888889,4.222222
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,"2,3,4-Trimethylpentane",CC(C)C(C)C(C)C,-4.800,5.415816,5.894012,0.0,0.0,8.424292,2.135779,4.271558,...,8.297793,35.071670,114.140851,4.390033,65.0,8.0,32.0,33.0,5.333333,1.888889
1044,Thiophenol,Sc1ccccc1,-2.120,5.059137,4.785854,0.0,0.0,8.720566,2.101003,4.202006,...,8.124151,33.544698,110.019021,8.463002,42.0,5.0,30.0,31.0,2.361111,1.666667
1095,Eriodictyol,Oc2cc(O)c1C(=O)CC(Oc1c2)c3ccc(O)c(O)c3,-3.620,16.608204,13.330263,0.0,0.0,26.321008,2.467430,4.934859,...,10.124509,55.372829,288.063388,8.729194,896.0,36.0,114.0,136.0,7.750000,4.472222
860,methyl nicotinate,COC(=O)c1cccnc1,-0.460,7.140017,6.873356,0.0,0.0,12.857279,2.214320,4.428639,...,8.703009,38.792641,137.047678,8.061628,121.0,11.0,44.0,48.0,3.722222,2.444444
1126,2-Methylbutane,CCC(C)C,-3.180,3.047207,3.305183,0.0,0.0,5.226252,1.847759,3.695518,...,6.834109,27.254130,72.093900,4.240818,18.0,2.0,16.0,14.0,3.361111,1.333333

In [3]:
from pycaret.regression import setup
exp = setup(train, target='logS', ignore_features=["name", "smiles"])

In [4]:
exp.compare_models(exclude=["mlp", "gbr", "xgboost", "lightgbm"])

ExtraTreesRegressor(n_jobs=-1, random_state=8984)

In [5]:
base_model = exp.create_model('et')
tuned_model = exp.tune_model(base_model, n_iter=5, optimize='mae')

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Fitting 10 folds for each of 5 candidates, totalling 50 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [6]:
exp.evaluate_model(tuned_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [7]:
final_model = exp.finalize_model(tuned_model)
test_pred = exp.predict_model(final_model, data=test)